language: php
php:
    - 5.6
before_install:
    - nvm install 5.1 && nvm use 5.1
install:
    - make vendor
    - npm install -g casperjs
script:
    - CASPER_HOME=http://localhost/ make test-phpunit test-php test-js test-casper CASPER_ARGS=
