language:
  - php
  - node_js
php:
  - 5.5
install:
  - npm install
  - npm install -g casperjs
script:
    - CASPER_HOME=http://localhost/ make test-phpunit test-php test-js test-casper CASPER_ARGS=
